// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "skeleton/app/types"

const TableNameUserModel = "users"

// UserModel mapped from table <users>
type UserModel struct {
	ID         int32                `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name       string               `gorm:"column:name;type:varchar(50)" json:"name"`
	Age        int32                `gorm:"column:age;type:int" json:"age"`
	Address    string               `gorm:"column:address;type:varchar(50)" json:"address"`
	Role       string               `gorm:"column:role;type:varchar(50)" json:"role"`
	Rule       string               `gorm:"column:rule;type:varchar(50)" json:"rule"`
	UpdateTime types.ModelFieldTime `gorm:"column:update_time;type:timestamp;default:now()" json:"update_time"`
}

// TableName UserModel's table name
func (*UserModel) TableName() string {
	return TableNameUserModel
}
